### ISSUE TITLE
Differences from latex-lsp/evince-synctex

### ISSUE THREAD

**Issue by schneiderfelipe** [Vinno97/evince-synctex#1]
Hi, thanks for the project.
I was wondering, what differs this project from [latex-lsp/evince-synctex](https://github.com/latex-lsp/evince-synctex) (other than yours being probably more consistently maintained)?

**Comment by Vinno97** [comment]
Even though our projects have identical names, I wasn't aware of that project yet! We all drew inspiration from  [gauteh/vim-evince-synctex](https://github.com/gauteh/vim-evince-synctex), I think. 

The main difference between [latex-lsp/evince-synctex](https://github.com/latex-lsp/evince-synctex) and this project is my superior documentation 🙂! No in all seriousness, I think it's just that this project is just written in shell script instead of Python. Though until the merging of #3, it's also still reliant on Python.
